name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 src tests

    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest tests

    - name: Build Docker Image
      run: |
        docker build -t my-ml-app:latest .

    - name: Push Docker Image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker tag my-ml-app:latest $DOCKER_USERNAME/my-ml-app:latest
        docker push $DOCKER_USERNAME/my-ml-app:latest
